dependencies:
  - name: rpe-feature-toggle-api
    version: ~3.1.0
    repository: '@hmctspublic'
    tags:
      - rpe-feature-toggle-cav-frontend
  - name: nodejs
    version: 1.3.1
    repository: '@hmctspublic'
  - name: redis
    version: 5.1.2
    repository: '@stable'
  - name: idam-pr
    version: ~2.1.3
    repository: '@hmctspublic'
    tags:
      - idam-pr-cav-frontend
